"""rename department

Revision ID: fed0958d77e7
Revises: ea5a64e36b0f
Create Date: 2024-04-10 23:19:28.466168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed0958d77e7'
down_revision = 'ea5a64e36b0f'
branch_labels = None
depends_on = None


def upgrade():
     # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
